CRUD/Models/Classe/Cliente.cs
using CRUD.Models.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Models.Classe
{
    public class Cliente
    {
        public int Id { get; set; }
        public string Razao_Social { get; set; }
        public string Cnpj { get; set; }
        public DateTime Data_Fundacao { get; set; }
        public decimal Capital { get; set; }
        public bool Quarentena { get; set; }
        public Status_Cliente status_cliente { get; set; }
        public Classificacao classificacao { get; set; }

    }
}

CRUD/Models/Enum/Classificacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Models.Enum
{
    public enum Classificacao
    {
        A,
        B,
        C
    }
}

CRUD/Models/Enum/Status_Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Models.Enum
{
    public enum Status_Cliente
    {
        Ativo, 
        Inativo 
    }
}

CRUD/Controllers/FormularioController.cs
using CRUD.IRepositorio;
using CRUD.Models.Classe;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CRUD.Controllers
{
    public class FormularioController : Controller
    {
        private readonly ICliente_Repositorio _repositorio;


        public FormularioController(ICliente_Repositorio repositorio)
        {
            _repositorio = repositorio;
        }

        public IActionResult Index()
        {
            IList<Cliente> clientes = _repositorio.Listar();
            return View(clientes);
        }

        public IActionResult Cadastro()
        {
            var cliente = new Cliente();
            return PartialView(cliente);
        }

        [HttpPost]
        public IActionResult Cadastrar(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _repositorio.Adiciona(cliente);
                return RedirectToAction("Index");
            }
            else
            {
                return View("Cadastro", cliente);
            }
        }

        public IActionResult Detalhar(int id)
        {
            var cliente = _repositorio.Detalhar(id);
            return PartialView(cliente);
        }

        public IActionResult Deletar(int id)
        {
            var cliente = _repositorio.Detalhar(id);
            return PartialView(cliente);
        }
        [HttpPost]
        public IActionResult Apagar(int id)
        {
            _repositorio.Remover(id);
            return RedirectToAction("Index");
        }
        
        public IActionResult Atualizar(int id)
        {
            var cliente = _repositorio.Detalhar(id);
            return PartialView(cliente);
        }
        [HttpPost]
        public IActionResult Editar(int id, Cliente cliente)
        {
            var c = new Cliente();
            c.Id = id;
            c.Razao_Social = cliente.Razao_Social;
            c.Cnpj = cliente.Cnpj;
            c.Capital = cliente.Capital;
            c.Data_Fundacao = cliente.Data_Fundacao;
            c.Quarentena = cliente.Quarentena;
            c.status_cliente = cliente.status_cliente;
            c.classificacao = cliente.classificacao;
            _repositorio.Alterar(c);
            return RedirectToAction("Index");
        }
    }
}

CRUD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRUD.Models;

namespace CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

CRUD/Views/Formulario/Atualizar.cshtml
@using CRUD.Models.Classe

@model Cliente

<h1>Alterar Empresa</h1>

<form asp-action="Editar" asp-controller="Formulario" asp-route-id="@Model.Id" method="post">
    <div class="form-group">
        <b>ID:</b> @Model.Id
    </div>
    <div class="form-group">
        <b>Razão Social:</b>
        <input type="text" asp-for="Razao_Social" class="form-control" value="@Model.Razao_Social" />
    </div>
    <div class="form-group">
        <b>CNPJ:</b>
        <input type="text" asp-for="Cnpj" class="form-control" value="@Model.Cnpj" />
    </div>
    <div class="form-group">
        <b>Data Fundação:</b>
        <input type="date" asp-for="Data_Fundacao" class="form-control" value="@Model.Data_Fundacao.ToString("dd/MM/yyyy")" />
    </div>
    <div class="form-group">
        <b>Capital:</b>
        <input type="number" asp-for="Capital" class="form-control" value="@Model.Capital" />
    </div>
    <div class="form-group">
        <b>Status do Cliente:</b>
        <select class="form-control" asp-for="status_cliente">
            <option selected="@Model.status_cliente" value="@Model.status_cliente"></option>
            <option value="Ativo">Ativo</option>
            <option value="Inativo">Inativo</option>
        </select>
    </div>
    <div class="form-group">
        <b>Quarentena:</b>
        <select class="form-control" asp-for="Quarentena">
            <option selected="@Model.Quarentena" value="@Model.Quarentena"></option>
            <option value="True">True</option>
            <option value="False">False</option>
        </select>
    </div>
    <div class="form-group">
        <b>Classificação:</b>
        <select class="form-control" asp-for="classificacao">
            <option selected="@Model.classificacao" value="@Model.classificacao"></option>
            <option value="A">A</option>
            <option value="B">B</option>
            <option value="C">C</option>
        </select>
    </div>
    <div class="form-group" style="text-align:right">
        <input type="submit" value="Salvar" class="btn btn-outline-warning">
        <input type="button" value="Fechar" class="btn btn-outline-info" data-dismiss="modal" />
    </div>
</form>

CRUD/Views/Formulario/Cadastro.cshtml
@using CRUD.Models.Classe

@model Cliente

<h1>Formulário</h1>

<form asp-action="Cadastrar" asp-controller="Formulario" method="post">
    <fieldset><h3>Cliente</h3></fieldset>
    <div class="form-group">
        <label asp-for="Razao_Social">Razao Social</label>
        <input type="text" class="form-control" asp-for="Razao_Social" />
    </div>
    <div class="form-group">
        <label asp-for="Cnpj">CNPJ</label>
        <input type="text" class="form-control" asp-for="Cnpj" /><br />
    </div>
    <div class="form-group">
        <label asp-for="Data_Fundacao">Data Fundada</label>
        <input type="date" asp-for="Data_Fundacao" /><br />
    </div>
    <div class="form-group">
        <label asp-for="Capital">Capital</label>
        <input type="number" class="form-control" asp-for="Capital" /><br />
    </div>
    <div class="form-group" style="text-align:right">
        <input type="submit" value="Cadastrar" class="btn btn-outline-success" />
        <input type="button" value="Fechar" class="btn btn-outline-info" data-dismiss="modal">
    </div>
</form>

CRUD/Views/Formulario/Deletar.cshtml
@using CRUD.Models.Classe

@model Cliente

<h1>Deletar Empresa</h1>

<p><b>ID: </b>@Model.Id</p>
<p><b>Razão Social: </b> @Model.Razao_Social</p>
<p><b>CNPJ: </b> @Model.Cnpj</p>
<p><b>Fundado em: </b>@Model.Data_Fundacao.ToString("dd/MM/yyyy")</p>
<p><b>Capital: </b> @Model.Capital</p>
<p><b>Qaurentena: </b> @Model.Quarentena</p>
<p><b>Status do Cliente: </b>@Model.status_cliente</p>
<p><b>Classificação: </b>@Model.classificacao</p>

<form asp-action="Apagar" asp-controller="Formulario" asp-route-id="@Model.Id" method="post">
    <div class="form-group" style="text-align:right">
        <input type="submit" value="Remover" class="btn btn-outline-danger">
        <input type="button" value="Fechar" class="btn btn-outline-info" data-dismiss="modal">
    </div>
</form>

CRUD/Views/Formulario/Detalhar.cshtml
@using CRUD.Models.Classe

@model Cliente

<h1>Detalhes da Empresa</h1>

<p><b>ID: </b> @Model.Id</p>
<p><b>Razão Social: </b> @Model.Razao_Social</p>
<p><b>CNPJ: </b> @Model.Cnpj</p>
<p><b>Fundado em: </b> @Model.Data_Fundacao.ToString("dd/MM/yyyy")</p>
<p><b>Capital: </b> @Model.Capital</p>
<p><b>Qaurentena: </b> @Model.Quarentena</p>
<p><b>Status do Cliente: </b> @Model.status_cliente</p>
<p><b>Classificação: </b> @Model.classificacao</p>
<div class="form-group" style="text-align:right">
    <input type="button" value="Fechar" class="btn btn-outline-info" data-dismiss="modal" />
</div>

CRUD/Views/Formulario/Index.cshtml
@using CRUD.Models.Classe

@model IList<Cliente>
<h4> Cadastrar Empresa</h4>
<i type="button" class="btn btn-success mt-3 mb-4 btn_cadastrar material-icons">add</i>
<table class="table table-hover text-center">
    <thead>
        <tr>
            <th>ID</th>
            <th>Razao Social</th>
            <th>CNPJ</th>
            <th>Data de Fundação</th>
            <th>Capital</th>
            <th>Quarentena</th>
            <th>Status Cliente</th>
            <th>Classificação</th>
            <th>Detalhar</th>
            <th>Editar</th>
            <th>Remover</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cliente in Model)
        {
            <tr>
                <td>@cliente.Id</td>
                <td>@cliente.Razao_Social</td>
                <td>@cliente.Cnpj</td>
                <td>@cliente.Data_Fundacao.ToString("dd/MM/yyyy")</td>
                <td>R$ @cliente.Capital</td>
                <td>@cliente.Quarentena</td>
                <td>@cliente.status_cliente</td>
                <td>@cliente.classificacao</td>
                <td><i type="button" class="btn btn-block btn-info details material-icons" data-id="@cliente.Id">comment</i></td>
                <td><i type="button" style="color:white" class="btn btn-block btn-warning edit material-icons" data-id="@cliente.Id">edit</i></td>
                <td><i type="button" class="btn btn-block btn-danger delete material-icons"  data-id="@cliente.Id">delete</i></td>
            </tr>
        }
    </tbody>
</table>
<!--Modal Centralizado-->
<div class="modal fade" id="myModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" style="background-color:silver">
                <div id="conteudoModal">

                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        $(function () {
            $(".details").click(function () {
                let id = $(this).attr("data-id");
                $("#conteudoModal").load("Formulario/Detalhar/" + id, function () {
                    $("#myModal").modal("show");
                })
            });

            $(".edit").click(function () {
                let id = $(this).attr("data-id");
                $("#conteudoModal").load("Formulario/Atualizar/" + id, function () {
                    $("#myModal").modal("show");
                })
            });

            $(".delete").click(function () {
                let id = $(this).attr("data-id");
                $("#conteudoModal").load("Formulario/Deletar/" + id, function () {
                    $("#myModal").modal("show");
                })
            });

            $(".btn_cadastrar").click(function () {
                $("#conteudoModal").load("Formulario/Cadastro", function () {
                    $("#myModal").modal("show");
                })
            });

        });
    </script>
}

CRUD/Views/Home/Index.cshtml
<h1>Projeto Web Junior ASP.Net Core </h1>

<h4>Entity framework</h4>
<h4>Asp.Net Core MVC</h4>
<h4>Injeção de Depedencia</h4>
<h4>Jquery</h4>
<h4>Bootstrap</h4>

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Index">Formulário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>